### ISSUE TITLE
Add support for python 3+

### ISSUE THREAD

**Issue by Dmitrij-Golubovskij-Bose** [sch3m4/pyadb#14]
Are you able to do provide support for Python 3? There is a similar version which is called pyadb3, but it has issues with getting device list.

**Comment by sch3m4** [comment]
this is a WIP with the latest versions of ADB but should be fixed now, thanks for reporting it!

**Comment by Dmitrij-Golubovskij-Bose** [comment]
No problem, thanks for support!
